Resources:
  AWSConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: !Ref ConfigRuleName
      Description: >-
        A config rule that checks whether the root user access key is
        available. The rule is COMPLIANT if the user access key does not exist.
        If any statement has 'Effect': 'Allow' with 'Action': '*' over
        'Resource': '*', the rule is NON_COMPLIANT.
      Scope:
        ComplianceResourceTypes:
          - 'AWS::IAM::User'
      Source:
        Owner: AWS
        SourceIdentifier: IAM_ROOT_ACCESS_KEY_CHECK
Parameters:
  ConfigRuleName:
    Type: String
    Default: iam-root-access-key-check
    Description: The name that you assign to the AWS Config rule.
    MinLength: '1'
    ConstraintDescription: This parameter is required.
Metadata: {}
Conditions: {}
