Resources:
  AWSConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: !Ref ConfigRuleName
      Description: >-
        A config rule that checks whether the IAM password policy is configured according to current compliance requirements.
        If any statement has 'Effect': 'Allow' with 'Action': '*' over
        'Resource': '*', the rule is NON_COMPLIANT.
      InputParameters:
        RequireUppercaseCharacters: true
        RequireUppercaseCharacters: true
        RequireUppercaseCharacters: true
        RequireUppercaseCharacters: true
        MinimumPasswordLength: !Ref MinimumPasswordLength
        PasswordReusePrevention: !Ref PasswordReusePrevention
        MaxPasswordAge: !Ref MaxPasswordAge
      Scope:
        ComplianceResourceTypes:
          - 'AWS::IAM::User'
      Source:
        Owner: AWS
        SourceIdentifier: IAM_PASSWORD_POLICY
Parameters:
  ConfigRuleName:
    Type: String
    Default: iam-password-policy
    Description: The name that you assign to the AWS Config rule.
    MinLength: '1'
    ConstraintDescription: This parameter is required.
  MinimumPasswordLength:
    Type: Number
    Default: 14
    Description: The minimum number of characters allowed in an IAM user password.
    ConstraintDescription: This parameter is required.
  PasswordReusePrevention:
    Type: Number
    Default: 24
    Description: Number of passwords before allowing reuse.
    ConstraintDescription: This parameter is required.
  MaxPasswordAge:
    Type: Number
    Default: 90
    Description: Number of days before password expiration.
    ConstraintDescription: This parameter is required.
Metadata: {}
Conditions: {}
